### ISSUE TITLE
Percentages less than 1

### ISSUE THREAD

**Issue by phillip-haydon** [ndsvw/Fluent-Random-Picker#10]
At the moment the lowest you can have is 1% but if I want a value to be returned 0.0001% of the time I cannot do it.

**Comment by ndsvw** [comment]
Hi,

This has actually a reason.
Using ```int``` as datatype allows checking that all percentages sum up to exactly 100.
There is also an algorithm used that calculates the sum of multiple of the values.

If ```double``` or ```float``` are used instead of ```int```, this could probably cause problems when summing up the weights/percentages, and it would require working with deltas for comparison. But if multiple very small percentages would be specified, this could maybe result in a situation in which some values will never be picked.

That's why I'm careful with this...

---

But it's hypothetically already possible to achieve what you are trying to do by using ```WithWeight``` instead of ```WithPercentage```.
This is how it could look like:

```c#
Out.Of().Value('a').WithWeight(1)
        .AndValue('b').WithWeight(9999)
        .PickOne();
```

In this case, the picked value is 'a' in 0.0001% of the cases and 'b' in 99.9999% of the cases.

**Comment by phillip-haydon** [comment]
That might work. I'm trying to build a loot drop and currently do something like:

Item 1: 0.3D
Item 2: 0.1D
Item 3: 0.001D

Then take next double from random and say:

for each item
if rnd <= item.rarity
 return item

If nothing matches no item is dropped. 

I'll try using weights to see if I can achieve the same thing.

**Comment by phillip-haydon** [comment]
So it appears to work ok, but the API is a bit tricky to work with due to it's fluent nature. 

For example you cannot iterate over a bunch of options to add a value and weight, then call PickOne or such after.

If you use the `.Values(...)` and `.WithWeights(...)` you can avoid iterating over, however you have to assume that the order of the values and weights is consistent to ensure they don't change resulting in the wrong weights being assigned to the wrong values.

**Comment by ndsvw** [comment]
Not sure whether I understand it completely. Would one of these features help you?
1) There is a class (e.g. 'ValueWeightPair' with 2 properties 'Weight'/'Percentage' and 'Value') **as part of FluentRandomPicker** and you can create a List&lt;ValueWeightPair&gt; and pass it to the Fluent API somehow.

or

2) There is a class **in your code** that has properties like 'Value' and 'Weight'/'Percentage' and you want to pass a collection of it to FluentRandomPicker. This would probably also require passing 2 selectors (e.g. `x => x.Value` and `x => x.Weight`) to FluentRandomPicker because FluentRandomPicker does not know the type otherwise.

**Comment by phillip-haydon** [comment]
So I have 2 use cases. 1 is picking from a fixed number of items which I'm now using your libary for rather than rolling my own codes. (thanks ^^) 

The 2nd is for a random item drop. The drops are stored in the database, at the moment they are based on weights as rarity. 

So I would like to do something like...
```
var options = Out.Of().WeightedValues(lootable.Select(x => new WeightedValue(x, x.Weight));

var drop = options.PickOne();
```

Unsure what the beach api approach is. Right now I pull them and do something like:

```
            var chance = new Random().Next(0, 100_000);

            foreach (var loot in LootPool.OrderByDescending(x => x.Rarity))
            {
                if (chance <= loot.Rarity)
                {
                    return loot;
                }

                chance -= loot.Rarity;
            }

            return new NoLoot();
```

**Comment by ndsvw** [comment]
Thanks for the explanation. I'll probably implement something like this in the near future.

**Comment by ndsvw** [comment]
I closed this, because this is initially about percentages and the fact that they can't be lower than 1.
@phillip-haydon For your 2nd suggestion, see #11.
