### ISSUE TITLE
Create implementation of `IRandomNumberGenerator` that is cryptographically secure

### ISSUE THREAD

**Issue by shoter** [ndsvw/Fluent-Random-Picker#4]
Currently FRP is using only Random() which is cryptographically unsecure. It is going to be flagged as major flaw by a lot of static code analyzers (i.e veracode). Adding new interface to handle random number generation in more secure way would be great.
Also there should be a way to exchange currently used random number generator.

**Comment by ndsvw** [comment]
Hi,

> Also there should be a way to exchange currently used random number generator.

That's already possible.
You can pass it as an argument of the Of() method and the code uses it everywhere.
If someone has written a new RNG (it has to implement the interface [IRandomNumberGenerator](https://github.com/ndsvw/Fluent-Random-Picker/tree/main/Fluent-Random-Picker/Random ), you could instantiate it (e.g. `var rng = new SecureRandomNumberGenerator()`) and pass it (`Out.Of(rng)...`).

I think, it makes sense to implement a cryptographically secure one (probably based on [RNGCryptoServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rngcryptoserviceprovider?redirectedfrom=MSDN&view=net-5.0) because it's already part of .Net) as part of the package, so that the user has the choice and does not have to implement it himself/herself. But I'm not sure about making the cryptographically secure one the default option because of performance reasons.
