### ISSUE TITLE
How can I give a small pool of reference types and pick a large number of items?

### ISSUE THREAD

**Issue by SapiensAnatis** [ndsvw/Fluent-Random-Picker#48]
Version: 3.4.0

I am trying to use the following code to randomly generate some drops for a game:

```csharp
private static IEnumerable<DropEntity> GenerateDrops(QuestDropInfo questDropInfo)
{
    int totalQuantity = (int)Math.Round(questDropInfo.Drops.Sum(x => x.Quantity));

    IPick<DropEntity> randomBuilder = Out.Of()
        .PrioritizedElements(questDropInfo.Drops)
        .WithWeightSelector(x => x.Weight);

    return randomBuilder.Pick(totalQuantity);
}
```

`questDropInfo` is a drop table with the following example JSON representation. The `Weight` property is the rounded value of `Quantity * 100`. 

```json
[
   {
      "_Id": 201009001,
      "_Quantity": 50
   },
   {
      "_Id": 40050045,
      "_Quantity": 0.1
   },
   {
      "_Id": 103001003,
      "_Quantity": 10
   }
]
```

I'm using `totalQuantity` as I want the items to be weighted in such a way that increasing the average quantity for one item does not make the other items less common.

When I run this code, FluentRandomPicker throws `NotEnoughValuesToPickException` presumably because I am trying to get 60 drops from a list with 3 values. I wanted to evenly distribute the drops based on the above weighting and generate many more items than I pass in. 

The [docs](https://github.com/ndsvw/Fluent-Random-Picker#picking-multiple-values) show an example where 5 values are picked from a picker with 4 values, but is this case different because I'm working with reference types which can't easily be cloned?

**Comment by SapiensAnatis** [comment]
Right after I posted this, I figured out a better way to do it by having my static method return the picker and then just using `PickOne()` in a loop to assign the drops per enemies -- this is effectively what I was doing anyway except with a `Stack` after getting the entire list.

I'll leave this open in case you do deem this worthy of addressing. Love the package by the way!

**Comment by ndsvw** [comment]
Hi,

Thanks for pointing this out. I was able to reproduce the problem and this looks like a bug.

I'll probably release a fix until the end of the week.

Then, will be able to call `Pick(500)`, even when there are only 2 values, as long as you don't call 'PickDistinct(n)` with < n items.

---

BTW: You mentioned reference types / values types. It does not matter whether the item is a value type or reference type. When working with reference types and calling `Pick(500)` when there are 2 items, it'll pick lots of references to the same 1 or 2 item(s) located somewhere on the heap, but that's normal Dotnet behavior. Producing actual clones should not be done by this library, because there are different ways to do it and this is a decision for the caller side.

To make it clearer: This behavior is expected to be possible:

```
var picked = Out.Of(new [] { new object(), new object(), new object() }.Pick(2).ToArray();
picked[0] == picked[1] // can return true
```

And if you don't want duplicates, there is `PickDistinct`.

**Comment by SapiensAnatis** [comment]
Thanks for the quick reply!

I didn't actually try the example in the docs and assumed it worked -- so value vs. reference type was  all I could come up with. But thank you for the clarification.
